version: "3.9"

services:
  ticketing-api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    image: ticketing-api:local
    env_file:
      - ./services/api/.env.docker
    ports:
      - "4000:4000"
    command: node dist/index.js
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped

  seatlock-worker:
    image: ticketing-api:local
    env_file:
      - ./services/api/.env.docker
    command: node dist/worker.js
    depends_on:
      - ticketing-api
    restart: unless-stopped

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    image: ticketing-web:local
    environment:
      NEXT_PUBLIC_API_URL: http://ticketing-api:4000
    ports:
      - "3000:3000"
    depends_on:
      - ticketing-api
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ticketing
      POSTGRES_PASSWORD: ticketing
      POSTGRES_DB: ticketing
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
